### ISSUE TITLE
EnviroMine compatibility

### ISSUE THREAD

**Issue by PitchBright** [TeamMetallurgy/Aquaculture#14]
I think because the Fish have some special tags on them for their Weight in LBS… they aren't recognized as items that can have Rot Times on them, in Enviromine. Can you look into the rot mechanics and see if something can be done there so that Fish can be set to Rot into other items (such as Rotten Food) in Enviromine.

**Comment by Glassmaker** [comment]
Will see if it's possible :)

**Comment by Glassmaker** [comment]
The good news: was able to figure it out, it adds an NBT tag to foods items, so changing the fish to a food item would make it rot with EnviroMine.

![2016-03-05_11 39 11](https://cloud.githubusercontent.com/assets/5352172/13546703/03a28692-e2c7-11e5-894c-a1fce582e454.png)

The bad news: Can't convert all the foods to food items due to loot and food share the same master item, therefore changing that would make neptunium, tin can, message in a bottle, etc.. rot.

Upon that, it better to split them to two master items, but splitting them would break backwards compatibility, so it would make sense to do it in 1.8.9.

**Comment by PitchBright** [comment]
You should be okay to go ahead and do it in 1.7.10 because Enviromine makes us manually add and config our subitems individually. So users would actually have to activate rot on the neptunium, tin can, bottles, etc… on purpose. :-)

**Comment by Glassmaker** [comment]
In my testing rot is enable on all food items by default, the test was using the latest version (1.3.124) at the time of writing, so no go for 1.7.10.

**Comment by PitchBright** [comment]
Glassmaker discovered that I had a typo in my config file. AC and EM **ARE** compatible on the fish rot. I'm an idiot.

item.Fish not item.fish
