### ISSUE TITLE
Villager Trades

### ISSUE THREAD

**Issue by Shinob1i** [TeamMetallurgy/Aquaculture#165]
Sorry, I don't really understand github that much, so I didn't know where to put this question. Would you be able to tweak the fisherman villager trades in order to be able to trade the Aquaculture fish with him? If you're not really interested in doing such, or you already have and I just never noticed somehow, you can just ignore this.

**Comment by sscards55** [comment]
@Shadowclaimer, is the creative director of the mod, and the one that can give the most probable answer

**Comment by GirafiStudios** [comment]
One of the goals of Aquaculture have always been that it can be added or removed from any world - without there being any issues. Which is why Aquaculture won't ever have any worldgen etc.
Adding more trades to a villager - and then removing Aquaculture would break that villagers trading completely.
Also adding all the Aquaculture Fish would completely flood the trade.
There is some mods out there, that allows you to add trades to villagers yourself though :) Not quite sure if they're updated though.
