### ISSUE TITLE
More loottable performance issues

### ISSUE THREAD

**Issue by Darkere** [TeamMetallurgy/Aquaculture#175]
Hello. I just noticed again that aquaculture is appearing on our profiling due to loottables.
Again it is caused by the Industrial Foregoing marine fisher, fishing automatically. 

![image](https://user-images.githubusercontent.com/4283717/101316877-aa95f380-385d-11eb-8d54-71d01c21ff0f.png)

As far as I can tell this profile ran with just 2! Fisher running. 
Full Profiling -> https://spark.lucko.me/#lS2O25IRcl

A quick look at the code, this method really needs some optimization/caching. :)

https://github.com/TeamMetallurgy/Aquaculture/blob/bbe7fa5f5fd8659a6abfaef70ae083aa5cab9b61/src/main/java/com/teammetallurgy/aquaculture/loot/BiomePropertiesPredicate.java#L63

**Comment by GirafiStudios** [comment]
Thank you for coming back for an update on this!
I need to rewrite this anyways, as Forge decided to add back in the BiomeDictionary again anyways (Lex had said multiple times that it wouldn't be possible, due to Biome registry changes), so I rewrote it based on the vanilla Biome Category system.
So yea I'll have caching in mind, when I need to rewrite this anyways :)
Isn't it less lag than last time though? Seems it was 9.28% last time and now it's down to 3.46%. I'm not sure how many you were running the previous time though.

**Comment by Darkere** [comment]
Pretty sure I placed down around twenty last time. That's honestly the reason I am back so quickly... Expecting this to go up really quickly as more people use them.

**Comment by GirafiStudios** [comment]
I've now released AQ2 version 2.1.7, which should have caching working :)
If you could do some profiling for it, that would be great! (Preferably with 2 fishers running, to compare exact numbers to your previous profiling)
