### ISSUE TITLE
[Suggestion] Data pack support for fish fillets

### ISSUE THREAD

**Issue by ChloeDawn** [TeamMetallurgy/Aquaculture#209]
I want to add other mods fish to be able to be filleted but it seems I have to write a mod to do it. It would be nice if it could be configured with a data pack.

**Comment by GirafiStudios** [comment]
Due to the nature of how our system works, that would not be possible - as that would break our entire weight system (Off by default, but some people only use the mod for that).
Making it possible through CraftTweaker is something I'll look into for sure though. Thought I had already done it tbf., must have never gotten around to it.
