### ISSUE TITLE
Aquaculture Config breaks on new versions for forge for 1.16.5

### ISSUE THREAD

**Issue by ModernGamingWorld** [TeamMetallurgy/Aquaculture#212]
Best way to to explain this one to you is to have you look at this issue on Ae2 github as your config is doing the samething as theirs is https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4991

**Comment by GirafiStudios** [comment]
Unable to reprocuce with Forge version 36.0.42 and Aquaculture verison 2.1.15.
It may happen under certain circumstances, after the changes to config hot-loading in Forge version 36.0.39 - I assume.
As it's a change in Forge, there is nothing I can do to retroactively fix the "issue" anyways - especially since it does not happen on newely generated configs.
Since it does create a backup file of the original config file (As you said in the issue you linked), simply just look what config values was changed in the old config file for the newly generated config file (If any changes was made at all)

**Comment by Rodg88** [comment]
It looks like Quark has managed to fix the issue here: https://github.com/Vazkii/Quark/pull/3022

And there's no changes between the backup files and the latest file that gets generated each time, it just generates new configs forever.

**Comment by GirafiStudios** [comment]
I still can't reproduce this at all. Are you able to get it to happen when just Aquaculture 2 is installed?

**Comment by GirafiStudios** [comment]
Managed to get it to occur, fixed it here https://github.com/TeamMetallurgy/Aquaculture/commit/da78aba6cc6abf750f2b80012e22f616cafdf4bf
New build will be on CurseForge shortly.
