### ISSUE TITLE
[1.11.2] According to Applecore, some of your food items have no hunger or saturation values

### ISSUE THREAD

**Issue by Sunconure11** [TeamMetallurgy/Aquaculture#23]
https://i.imgur.com/aduxR7b.png

**Comment by Sunconure11** [comment]
There's also a similar issue with the nutrition mod, relating to how you are registering food.

https://github.com/WesCook/Nutrition/pull/9#issuecomment-309187178

**Comment by Glassmaker** [comment]
![2017-06-18_02 13 55](https://user-images.githubusercontent.com/5352172/27256886-55fab028-53cc-11e7-8ff1-261dcddce5d6.png)
kinda detecting now on some items, so guess compat patch is needed for full support :)

**Comment by Sunconure11** [comment]
My pull for that repo is that compat patch, basically.

**Comment by WesCook** [comment]
Looks good.  Thanks @Glassmaker and @Sunconure11.

The partial support is probably due to oredicts.  I add a few things automatically like `listAllfishraw`.

Is the above commit a 1.11-only change, or will it be backported?  Just wondering if I should add Aquaculture entries to my 1.10 version as well.  Thanks!

**Comment by Glassmaker** [comment]
@WesCook, it's an easy fix, so it will be backported as people are still on 1.10.2 :)

**Comment by Glassmaker** [comment]
Aquaculture fixed versions (1.4.1.4 for 1.10.2, and 1.5.1.2 for 1.11.2) are up on curse. :)
