### ISSUE TITLE
All of the treasure in Aquaculture is classified as junk?

### ISSUE THREAD

**Issue by Mortichar** [TeamMetallurgy/Aquaculture#284]
So... luck of the sea is reducing my chances to get neptune's bounty, and all of the other chests? Because pretty much the first thing I did when I picked up this mod was enchant my fishing pole to catch all of the treasure and I have yet to catch anything, despite catching vanilla treasures.

[src/main/resources/data/aquaculture/loot_tables/gameplay/fishing/junk.json](https://github.com/TeamMetallurgy/Aquaculture/blob/ea4b320903bfbf2df62c0bab27d7b0ce1b6d1fd3/src/main/resources/data/aquaculture/loot_tables/gameplay/fishing/junk.json)

I read about this in several places (reddit, etc.), so it seems to be a known issue, yet I didn't see any issues here (open or closed) that have mentioned this? Is this... intentional?

**Comment by Mortichar** [comment]
Switched from a gold hook to a diamond one and switched to a pole without luck. Immediately caught a goldfish and box, after hours of trying with luck last night.

**Comment by sscards55** [comment]
You're reading outdated information. Neptunium items were considered junk in Aquaculture 1 (1.12 and below). In Aquaculture 2 (1.14 and above) they are considered treasure.

The reason that they were considered junk in earlier versions is because it was a workaround, I don't remember to what. However as of version 2, you will have better chances of fishing them if you use a fishing rock with luck of the sea.

If you read though the loottable that you linked you will see that there are no Neptunium items listed in it.

**Comment by Mortichar** [comment]
Okay, I get that for the case of neptunium, but what about the treasure chests? Why are those marked as junk?

**Comment by sscards55** [comment]
Huh. I don't actually know. This is a @Shadowclaimer question.

**Comment by GirafiStudios** [comment]
To not lower the chances of getting vanilla treasure. We get plenty of complaints regarding that already.
