### ISSUE TITLE
Neptune's Abilities Problems

### ISSUE THREAD

**Issue by ZhyuroKun** [TeamMetallurgy/Aquaculture#288]
Hey Aquaculture Team!

I Have Problems With These 2 Neptune Abilities:

• First: Neptune's Buoyancy Looks Like No Difference From Vanilla Buoyancy / Almost No Difference
It Feels Just Like Using The Levitation Effect In The Water

• Lastly: Neptune's Feast Doesn't Seem To Work
It Says If It Adds To The Number Of Fillets You Get

But Not So, Example:
• Still Get 1 Fillet From 1 Atlantic Herring
• Still Get 2 Fillet From 1 Brown Trout
• Still Get 3 Fillet From 1 Muskellunge

I've Tried It Many Times, But It's The Same
And What Is The Number Of Additional Fillets? 

It's Written More But No More
Does It Turn Out That There Is An Chance To Get More? 🤔

Notes: Maybe 1st Isn't A Problem, Just Barely Visible :)

**Comment by GirafiStudios** [comment]
1. The player need to sink a tiny amount still, otherwise it breaks swimming
2. Neptune´s Feast does work, it´s just not visible with all fish, without having the  "Enable weight for fish?"-config enabled. It´s based of the fish weight - the fish have some default weights they will always have, unless that config is turned on.
![image](https://user-images.githubusercontent.com/6305377/146369272-b06737c2-02d7-4de6-85d0-f2ed7a72cded.png)
![image](https://user-images.githubusercontent.com/6305377/146369297-6216b1ce-a4a7-4536-86b6-afec4f40e2f2.png)
