### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by UsernameNotActive** [TeamMetallurgy/Aquaculture#311]
I am unable to get any of the items and fishes while fishing.

**Comment by UsernameNotActive** [comment]
I found out that the problem was caused by datapacks. For some reason having any datapack will cause the fishing system to break.

**Comment by GirafiStudios** [comment]
What are you exactly changing with your datapack? :)
Also could you provide your datapacks, so I can try to reproduce this?

**Comment by GirafiStudios** [comment]
I´m not really familiar with vanilla tweak datapacks.
Could you provide links to the datapacks, so I´m sure I´m using the same ones as you? :)

**Comment by UsernameNotActive** [comment]
https://www.planetminecraft.com/data-pack/technical-enchant-for-1-17/
and 
https://vanillatweaks.net/picker/datapacks/
For what I tested, having any of the vanilla tweaks datapack creates the problem.

**Comment by GirafiStudios** [comment]
It is 100% caused by Techinchal Enchant, as it overwrites the vanilla fishing.json. Which is very weird of them to do, as they actually don´t make any changes to it. But they overwrite it after Aquaculture have added its loot tables to it.
Deleting the fishing.json in data\minecraft\loot_tables\gameplay\ should fix it :)
