### ISSUE TITLE
Question Cofig

### ISSUE THREAD

**Issue by LlNUS** [TeamMetallurgy/Aquaculture#371]
First of all, thank you for this beautiful mod <3

Would it be possible to be able to turn off mob spawning?

Tank you for your answer.

**Comment by Shadowclaimer** [comment]
There are no plans for any new config options at the moment.

**Comment by GirafiStudios** [comment]
There is ways to turn mob spawning off in all versions.
In newer versions it´s simply not possibly to add conigs, due to load order.

For 1.19+, you´ll need to use a resourcepack to disable them. https://github.com/TeamMetallurgy/Aquaculture/tree/master/src/main/resources/data/aquaculture/forge/biome_modifier
