### ISSUE TITLE
Craftweaker isnt able to effect some recipes in 1.18.2

### ISSUE THREAD

**Issue by Maelztrom** [TeamMetallurgy/Aquaculture#378]
The recipes that combine a knife and fish to get raw fillets are unable to be removed by crafttweaker.
removing all recipes from the crafting table leaves these recipes
removing by input of the knife or the fish leaves these recipes, removing by output of the fillets leaves these recipes
there's a config that disables them, but I thought I should mention those recipes are oddly not working with crafttweaker.

there is not a config that removes jellyfish and leeches from brewing potions, and they have the same functionality issue with craftweaker, nothing CT can do to let me disable jellyfish and leeches from being viable brewing ingredients.

**Comment by GirafiStudios** [comment]
The fish fillet recipes showing in JEI is a custom implemantation of getting them to show at all, CraftTweaker will never be able to tweak that in any way, which is why there is a config.

As for the brewing recipes, they're being added in the standard way, that any new brewing recipe would. I'm not familiar with how CraftTweaker removes brewing recipes, or if it can at all.
How you been able to remove brewing recipes from other mods without issues?

**Comment by Maelztrom** [comment]
craft tweaker let me use the aquaculture turtles to brew a potion of turtle master and remove all other recipes for  mundane potion ( only leech and jellyfish make a mundane potion in my modpack, no other ingredients do).

ill test removing a potion from another mod, but I'll have to find one to install first, standby
