### ISSUE TITLE
Relogging world causes Aquaculture fishing loot table to disappear/break (Forge 1.20.1)

### ISSUE THREAD

**Issue by goldrat1** [TeamMetallurgy/Aquaculture#451]
If I load up my Minecraft client (Forge 1.20.1, through Curseforge, no other mods other than Aquaculture) and join into a singleplayer world, I can catch Aquaculture fish fine, even with a normal fishing rod. 
However if I leave the world and join back into it, I cannot get any fish from the Aquaculture fishing loot tables at all. Any time I try to fish one out, it gives me either a vanilla Fish or literally nothing at all. 
Is this a problem with how the loot table is loaded on world load or something?

Steps to reproduce:
1. Load game and make/join world.
2. Observe that you can catch Aquaculture fish with a Fishing Rod.
3. Quit and rejoin world.
4. Observe that you can't.

This is on the latest version of Forge 1.20.1 (v47.3.5) on the latest version of Aquaculture (1.20.1-2.5.1)

**Comment by GirafiStudios** [comment]
Thank you very much for reporting!
I was honestly not expecting this to be reproduce with just Aquaculture, as 1.20.1 have been out for so long & nobody have ever noticed. But it was extremely easy to reproduce.

Fixed in https://github.com/TeamMetallurgy/Aquaculture/commit/f877b0c07a23f40f9edb500f6d6bb30e4a133eed

A new release will be out shortly
