### ISSUE TITLE
Can't smelt Tin Cans in RLCraft

### ISSUE THREAD

**Issue by Enyaron** [TeamMetallurgy/Aquaculture#58]
Unable to smelt Tin Can in RLCraft. Using the Just Enough Items mod it seems that the recipe doesn't work inside of RLCraft currently. Not sure if this is intended or a bug currently.
![2019-10-10_13 26 37](https://user-images.githubusercontent.com/32036640/66568731-efdb6a00-eb61-11e9-8ea0-9354430126f6.png)
![2019-10-10_13 27 02](https://user-images.githubusercontent.com/32036640/66568733-efdb6a00-eb61-11e9-9572-4da3f69b533f.png)

**Comment by GirafiStudios** [comment]
Thanks for your report!
Since RLCraft is a modpack they most likely changed something relating for outputting iron or tin nuggets in the Furnace with CraftTweaker - it works just fine with just Aquaculture 1 installed.
I would suggest reporting it to RLCraft, since it's changes on their side that's causing it.

**Comment by sscards55** [comment]
This is correct, I had confirmed this previously in the TeamMeltallurgy discord.
>RLCraft is removing all iron nugget recipes from the furnace, since tin cans produce a nugget the recipe also gets removed.
>`furnace.remove(<minecraft:iron_nugget>);`
