### ISSUE TITLE
No squids spawning?

### ISSUE THREAD

**Issue by zEpiixz** [TeamMetallurgy/Aquaculture#61]
So after i added this mod to my modpack and server we had no spawns of minecraft squid anymore.

**Comment by GirafiStudios** [comment]
Thanks for your report!
As of 1.13 Squids can now only spawn in rivers or any ocean biome - with various rarity depending on the biome, which makes them overall quite a bit rarer than previously.
Since Aquaculture 2 adds fish that's of course gonna make them a little rarer too, our fish have quite low weights though which should allow for vanilla and water mods from other mods to still spawn frequently. If you're looking in rivers they'll be very rare even without Aquaculture 2, your best bet would be to look in oceans - specifically in Warm Oceans or Lukewarm Oceans where they're easily found.
![aeTGbAo](https://user-images.githubusercontent.com/6305377/66838562-269bf080-ef65-11e9-8e16-3c999912411f.png)

**Comment by zEpiixz** [comment]
Ive got the problem. My console had an error where it said Aquaculutre2 River overfished please report to github. May that caused it?
